Estacionamento.MVC/Models/ErrorViewModel.cs
using System;

namespace Estacionamento.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Estacionamento.MVC/Models/MarcaModel.cs
namespace Estacionamento.MVC.Models
{
    public class MarcaModel
    {
        public int Id {get;set;}
        public string Marca {get;set;}

        public MarcaModel( string marca)
        {
            this.Marca = marca;
        }

        public MarcaModel()
        {
        }
    }
}

Estacionamento.MVC/Models/ModeloModel.cs
namespace Estacionamento.MVC.Models
{
    public class ModeloModel
    {
        public int Id {get;set;}
        public string Modelo {get;set;}

        public ModeloModel(string modelo)
        {
            this.Modelo = modelo;
        }

        public ModeloModel()
        {
        }
    }
}

Estacionamento.MVC/Models/RegistroModel.cs
using System;
using Microsoft.Extensions.Primitives;

namespace Estacionamento.MVC.Models
{
    public class RegistroModel
    {
        public int Id {get;set;}
        public string Nome {get;set;}
        public string Marca {get;set;}
        public string Modelo {get;set;}
        public string Placa {get;set;}
        public DateTime DataDeEntrada {get;set;}

        

    }
}

Estacionamento.MVC/Controllers/ListarController.cs
using Estacionamento.MVC.Repositorio;
using Estacionamento.MVC.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Estacionamento.MVC.Controllers {
    public class ListarController : Controller{
        RegistroRepositorio registroRepositorio = new RegistroRepositorio();
        MarcaRepositorio marcaRepositorio = new MarcaRepositorio();
        ModeloRepositorio modeloRepositorio = new ModeloRepositorio();
        RegistroViewModel registroViewModel = new RegistroViewModel ();

        [HttpGet]
        public IActionResult Index () {
            var registros = registroRepositorio.Listar ();
            registroViewModel.Registros = registros;

            return View (registroViewModel);
        }
        public IActionResult FiltrarRegistros(IFormCollection form){
            
            string data = form["data"];

            registroViewModel.Registros = registroRepositorio.Filtrar(data);

            return View(registroViewModel);
        }
    }
}

Estacionamento.MVC/Controllers/RegistroController.cs
using System;
using Estacionamento.MVC.Models;
using Estacionamento.MVC.Repositorio;
using Estacionamento.MVC.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Estacionamento.MVC.Controllers {
    public class RegistroController : Controller {
        RegistroRepositorio registroRepositorio = new RegistroRepositorio ();
        MarcaRepositorio marcaRepositorio = new MarcaRepositorio ();
        ModeloRepositorio modeloRepositorio = new ModeloRepositorio ();

        [HttpGet]
        public IActionResult Index () {
            var marcas = marcaRepositorio.Listar ();
            var modelos = modeloRepositorio.Listar ();

            RegistroViewModel registro = new RegistroViewModel ();
            registro.Marcas = marcas;
            registro.Modelos = modelos;

            return View (registro);
        }

        [HttpPost]
        public IActionResult Registrar (IFormCollection form) {
            RegistroModel registro = new RegistroModel ();
            registro.Nome = form["nome"];
            registro.Placa = form["placa"];
            registro.Marca = form["marca"];
            registro.Modelo = form["modelo"];
            registro.DataDeEntrada = DateTime.Parse (form["dataDeEntrada"]);
            registroRepositorio.Cadastrar (registro);

            return View ("_Sucesso");
        }

        [HttpGet]
        public IActionResult Listar () {
            RegistroRepositorio registroRepositorio = new RegistroRepositorio ();
            ViewData["registros"] = registroRepositorio.Listar ();

            return View ();
        }
    }
}

Estacionamento.MVC/Views/Home/Index.cshtml
@model Estacionamento.MVC.ViewModel.RegistroViewModel

<header>
    @{
        Html.RenderPartial("_HeaderNavBar");
    }

<h1>Bem vindo ao Tsukar</h1>

</header>

<form id="#formulario" action="Carro/Cadastrar" method="POST">
    <label>
        Nome
        <input type="text" name="nome">
    </label>
    <label>
        Marca do carro
        <input type="text" name="marca">
    </label>
    <label>
        Modelo do carro
        <input type="text" name="modelo">
    </label>
    <label>
        Placa do carro
        <input type="text" name="placa">
    </label>
    <label>
        Data Entrada
        <input type="date" name="dataDeEntrada">
    </label>
    <div class="double-field">
        <div>
            <label for="marca">Marca</label>
            <select id="marca" name="marca" required>
                <option value="" disabled selected>Selecione</option>
                @foreach (var marca in Model.Marcas)
                {
                    <option value="@marca.Marca">@marca.Marca</option>
                }
            </select>
        </div>
        <div>
            <label for="modelo">Modelo</label>
            <select id="modelo" name="modelo">
                <option value="" disabled selected>Selecione</option>
                @foreach (var modelo in Model.Modelos)
                {
                    <option value="@modelo.Modelo">@modelo.Modelo</option>
                }
            </select>
        </div>
    </div>
    <input type="submit" value="Cadastrar">
</form>

Estacionamento.MVC/Views/Shared/_HeaderNavBar.cshtml
<nav>
        <div class="section-container">
            <ul>
                 <li><a href='@Url.Action("Index", "Registro")'>Cadastrar</a></li>
                 <li><a id="bt-historico" asp-controller="Listar" asp-action="Index">Listar</a></li>             
            </ul>
        </div>
</nav>

Estacionamento.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <title>Agora Var - Tsukar</title>
    <link href="~/css/site.css" rel="stylesheet" type="text/css">
</head>
<body class="flex-container">

     @RenderBody()
    
    <footer id="#footer">
        <div class="footer-container">
            <address>
               Avenida Raimundo Pereira de Magalhães - SP 
                <br />
                Tsukar@email.com
                <br />
                11 1234 6789
            </address>
        </div>
    </footer>
</body>
</html>

Estacionamento.MVC/Views/Shared/_Sucesso.cshtml
 @{
        Html.RenderPartial("_HeaderNavBar");
    }
    
<h2>Sucesso!</h2>